version: "3.13"

services:
  travelapi:
    build:
      context: ./
      dockerfile: release.Dockerfile
    container_name: travel-api
    restart: always
    env_file:
      - app/dev.env
    volumes:
      - "./app:/app"
    ports:
      - "5000:5000"